### ISSUE TITLE
Missing from header

### ISSUE THREAD

**Issue by fooman** [magespecialist/m2-MSP_SMTP#2]
I am currently getting the below stack trace using version 2.3.5 with Magento 2.3.0. and using the Send Email button from the Admin Order view. I have had a quick look and believe this to be impacted by https://github.com/magento/magento2/issues/14952 but maybe a fallback could be added.

```2019/01/30 06:54:55 [error] 189#189: *884 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getEmail() on boolean in /var/www/vendor/msp/smtp/Mail/Transport.php:94
Stack trace:
#0 /var/www/generated/code/MSP/SMTP/Mail/Transport/Interceptor.php(37): MSP\SMTP\Mail\Transport->setRecipients()
#1 /var/www/vendor/msp/smtp/Mail/Transport.php(58): MSP\SMTP\Mail\Transport\Interceptor->setRecipients()
#2 /var/www/vendor/magento/framework/Interception/Interceptor.php(58): MSP\SMTP\Mail\Transport->sendMessage()
#3 /var/www/vendor/magento/framework/Interception/Interceptor.php(138): MSP\SMTP\Mail\Transport\Interceptor->___callParent('sendMessage', Array)
#4 /var/www/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(74): MSP\SMTP\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/vendor/magento/framework/Interception/Interceptor.php(135): Dotdigitalgroup\Email\Plugin\TransportPlugin->aroundSendMessage(Object(MSP\SMTP\Mail\Transport\Interceptor), Object(Closure))
#6 /var/www/vendor/ma" while reading response header from upstream, client: 172.17.0.2, server: localhost, request: "GET /admin/sales/order/email/order_id/80/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "example.com", referrer: "https://example.com/admin/sales/order/view/order_id/80/"```

**Comment by Mikito-San** [comment]
Please check if this issue is solved in 2.3.6 and let me know, thank you
